select * from postcallsurvey

SELECT 
Dateadd(DAY,0, (Datediff(DAY,0,dateTime))) as Date,
COUNT(CASE WHEN Q1 = 1 THEN 1 END) as 'Q1_YA',
COUNT(CASE WHEN Q1 = 2 THEN 1 END) as 'Q1_Tidak',
COUNT(CASE WHEN Q1 = null THEN 1 END) as 'Q1_NULL',
CONVERT(float(2),COUNT(CASE WHEN Q1 = 1 THEN 1 END)) / (COUNT(CASE WHEN Q1 = 1 THEN 1 END)+COUNT(CASE WHEN Q1 = 2 THEN 1 END)+COUNT(CASE WHEN Q1 = null THEN 1 END)) * 100 as 'Q1_YA%',
COUNT(CASE WHEN Q2 = 1 THEN 1 END) as 'Q2_YA',
COUNT(CASE WHEN Q2 = 2 THEN 1 END) as 'Q2_Tidak',
COUNT(CASE WHEN Q2 = null THEN 1 END) as 'Q2_NULL',
CONVERT(float(2),COUNT(CASE WHEN Q2 = 1 THEN 1 END)) / (COUNT(CASE WHEN Q2 = 1 THEN 1 END)+COUNT(CASE WHEN Q2 = 2 THEN 1 END)+COUNT(CASE WHEN Q2 = null THEN 1 END)) * 100 as 'Q2_YA%',
COUNT(CASE WHEN Q3 = 5 THEN 1 END) as '5',
COUNT(CASE WHEN Q3 = 4 THEN 1 END) as '4',
COUNT(CASE WHEN Q3 = 3 THEN 1 END) as '3',
COUNT(CASE WHEN Q3 = 2 THEN 1 END) as '2',
COUNT(CASE WHEN Q3 = 1 THEN 1 END) as '1',
COUNT(ANI) as 'TotalResponden'
FROM postcallsurvey 
GROUP BY Dateadd(DAY,0, (Datediff(DAY,0,dateTime)))